// backend/src/profile/profile-media.error-codes.ts

export enum ProfileMediaAccessErrorCode {
  NOT_FOUND = 'NOT_FOUND',
  USER_BANNED = 'USER_BANNED',
  USER_INACTIVE = 'USER_INACTIVE',
  BLOCKED = 'BLOCKED',
  PRIVATE_ACCOUNT = 'PRIVATE_ACCOUNT',
  INVALID_MEDIA_CATEGORY = 'INVALID_MEDIA_CATEGORY',
}

export enum ProfileMediaDeleteErrorCode {
  NOT_FOUND = 'PROFILE_MEDIA_NOT_FOUND',
  ACCESS_DENIED = 'PROFILE_MEDIA_ACCESS_DENIED',
  BLOCKED = 'PROFILE_MEDIA_BLOCKED',
  INVALID_STATE = 'PROFILE_MEDIA_INVALID_STATE',
}
