# ---------- Stage 1: Builder ----------
FROM node:22-slim AS build

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY package*.json ./

RUN npm set registry https://registry.npmmirror.com \
    && npm set fetch-retries 5 \
    && npm set fetch-retry-factor 10

RUN --mount=type=cache,target=/root/.npm \
    npm ci

RUN chmod +x node_modules/.bin/next

COPY . .

COPY .env.production .env.production

RUN --mount=type=cache,target=/root/.npm \
    npm run build


# ---------- Stage 2: Runner ----------
FROM node:22-bullseye-slim AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

COPY --from=build /app/.env.production ./.env.production

EXPOSE 3000

CMD ["node", "server.js"]
