apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mywebsite-frontend
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/mywebsite-frontend:latest
          env:
            # Must match your Next.js code (NEXT_PUBLIC_API_BASE)
            - name: NEXT_PUBLIC_API_BASE
              value: "https://mywebsite-backend-xxxx.a.run.app"

            - name: NEXT_PUBLIC_BACKEND_URL
              value: "https://mywebsite-backend-xxxx.a.run.app"

          ports:
            - containerPort: 3000
