# ---------- Stage 1: Build ----------
FROM node:22-slim AS build

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y openssl libvips ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN npm set registry https://registry.npmmirror.com \
    && npm set fetch-retries 5 \
    && npm set fetch-retry-factor 10 \
    && npm set fetch-retry-mintimeout 20000 \
    && npm set fetch-retry-maxtimeout 120000 \
    && npm set strict-ssl false

# Copy package files first (cache-friendly)
COPY package*.json ./

# Install full dev dependencies for build & prisma
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy source code
COPY tsconfig*.json ./
COPY prisma ./prisma
COPY src ./src

# Generate Prisma Client
RUN npx prisma generate --schema=prisma/schema.prisma

# Build NestJS
RUN npm run build


# ---------- Stage 2: Runtime ----------
FROM node:22-slim AS runner

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y openssl curl libvips ffmpeg \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production
ENV PORT=4001
ENV DOCKER_ENV=true
ENV REDIS_URL=redis://redis:6379

COPY package*.json ./

# Install only production deps
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev

# Copy build output
COPY --from=build /app/dist ./dist

# Copy Prisma client + engines
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/node_modules/@prisma ./node_modules/@prisma

# Copy prisma folder (schema, migrations)
COPY --from=build /app/prisma ./prisma

EXPOSE 4001

CMD ["node", "dist/main.js"]
