// ==============================
// file: pages/api/me.ts
// ==============================
import type { NextApiRequest, NextApiResponse } from "next";

/**
 * Important:
 *
 * This API route runs only inside the Next.js frontend server.
 * It cannot read, validate, or decode the backend's HTTP-only session cookie
 * generated by Firebase Admin during Hybrid OAuth (Google/Facebook login).
 *
 * Do NOT use this route to check auth status.
 *
 * Always call:
 *   GET ${process.env.NEXT_PUBLIC_API_BASE}/auth/session-check
 *
 * That endpoint validates:
 *   - Firebase Admin session cookie
 *   - Google OAuth login
 *   - Facebook OAuth login
 *   - JWT / security checks
 *   - Cookie domain: .phlyphant.com
 *   - Firebase Service Account
 */

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    // Prevent caching entirely (security)
    res.setHeader("Cache-Control", "no-store");

    // API Base for production
    const API_BASE =
      process.env.NEXT_PUBLIC_API_BASE ||
      "https://api.phlyphant.com";

    return res.status(200).json({
      ok: true,
      note: "This Next.js API route is not connected to backend auth. Use backend route for real authentication.",
      recommendedAuthEndpoint: `${API_BASE}/auth/session-check`,

      // Useful for debugging or showing how to call OAuth login endpoints
      hybridOAuth: {
        googleLogin: `${API_BASE}/auth/google?origin=${encodeURIComponent(
          process.env.NEXT_PUBLIC_SITE_URL || "https://phlyphant.com"
        )}`,
        facebookLogin: `${API_BASE}/auth/facebook?origin=${encodeURIComponent(
          process.env.NEXT_PUBLIC_SITE_URL || "https://phlyphant.com"
        )}`,
      },
    });
  } catch {
    return res.status(500).json({ ok: false });
  }
}
